enum MainSceneStates {
  INTRO,
  IDLE,
  PLAY_START,
  RECEIVED_DATA,
  SPIN_STOPPING,
  SPIN_STOP,
  SHOW_WINS,
  FREESPINS_RETRIGGER,
  FREESPINS_ACTIVATE,
  FREESPINS_END,
  PLAY_FINISH,
  ROUND_FINISH
}

export default MainSceneStates;