const CLR_LIST_ENUM = {
    RED: '#ff0000',
    BLUE: '#0000ff',
    GREEN: '#008000',
    YELLOW: '#ffff00',
    ORANGE: '#ffa500',
    PURPLE: '#800080',
    PINK: '#ffc0cb',
    SALMON: '#fa8072',
    BROWN: 'a52a2a',
    BLACK: '#000000',
    LIGHTGRAY: '#d3d3d3',
    LIGHTGREEN: '#90ee90',
    DARKORANGE: '#ff4500',
    DARKBLUE: '#00008b',
    DARKRED: '#8b0000',
    DARKGRAY: '#222222',
    LIGHTGRAY: '#eeeeee'
};

export const data = [
    {
        id: 1,
        value: 80,
        text: '80',
        backgroundColor: CLR_LIST_ENUM.RED,
        color: CLR_LIST_ENUM.DARKGRAY,
    },
    {
        id: 2,
        value: 120,
        text: '120',
        backgroundColor: CLR_LIST_ENUM.BLUE,
        color: CLR_LIST_ENUM.LIGHTGRAY,
    },
    {
        id: 3,
        value: 15,
        text: '15',
        backgroundColor: CLR_LIST_ENUM.GREEN,
        color: CLR_LIST_ENUM.DARKGRAY,
    },
    {
        id: 4,
        value: 135,
        text: '135',
        backgroundColor: CLR_LIST_ENUM.YELLOW,
        color: CLR_LIST_ENUM.DARKGRAY,
    },
    {
        id: 5,
        value: 58,
        text: '58',
        backgroundColor: CLR_LIST_ENUM.PINK,
        color: CLR_LIST_ENUM.DARKGRAY
    },
    {
        id: 6,
        value: 'freeSpins',
        text: 'Free Spins',
        backgroundColor: CLR_LIST_ENUM.LIGHTGRAY,
        color: CLR_LIST_ENUM.DARKGRAY
    },
    {
        id: 7,
        value: 65,
        text: '65',
        backgroundColor: CLR_LIST_ENUM.PURPLE,
        color: CLR_LIST_ENUM.LIGHTGRAY,
    },
    {
        id: 8,
        value: 145,
        text: '145',
        backgroundColor: CLR_LIST_ENUM.DARKORANGE,
        color: CLR_LIST_ENUM.DARKGRAY,
    },
    {
        id: 9,
        value: 220,
        text: '220',
        backgroundColor: CLR_LIST_ENUM.LIGHTGREEN,
        color: CLR_LIST_ENUM.DARKGRAY,
    },
    {
        id: 10,
        value: 20,
        text: '20',
        backgroundColor: CLR_LIST_ENUM.DARKRED,
        color: CLR_LIST_ENUM.LIGHTGRAY,
    },
    {
        id: 11,
        value: 150,
        text: '150',
        backgroundColor: CLR_LIST_ENUM.DARKBLUE,
        color: CLR_LIST_ENUM.LIGHTGRAY,
    },
    {
        id: 12,
        value: 0,
        text: '0',
        backgroundColor: CLR_LIST_ENUM.BLACK,
        color: CLR_LIST_ENUM.LIGHTGRAY,
    },
    {
        id: 13,
        value: 350,
        text: '350',
        backgroundColor: CLR_LIST_ENUM.SALMON,
        color: CLR_LIST_ENUM.DARKGRAY,
    },
    {
        id: 14,
        value: 175,
        text: '175',
        backgroundColor: CLR_LIST_ENUM.ORANGE,
        color: CLR_LIST_ENUM.DARKGRAY,
    },
];